version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/chuhlomin/gbfs-go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
